config/routes.rb
Rails.application.routes.draw do
  
  
root "foods#index"
  
  devise_for :users

  resources :foods
      
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
  has_many :foods        

  def full_name

    "#{self.first_name} #{self.last_name}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!
  
    protected
      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
      end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]
  
  def index
    @foods = current_user.foods
  end

  def show
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(food_params)
    if @food.save
      redirect_to foods_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @food.update(food_params)
    redirect_to foods_path
    else
      render :edit
    end
  end

  def destroy
    @food.destroy
    redirect_to foods_path
  end

private
  def food_params
    params.require(:food).permit(:item, :group)
  end

  def set_food
    @food = current_user.foods.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only:[:show, :edit, :update]

  def index
    
  end

  def show
  end

  def new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to foods_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to new_user_registration_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name)

    def set_user
      @user = current_user.foods.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_form.html.erb
<h1><%= @food.id ? 'Edit Food' : 'Create Food' %></h1>
<hr />
<%= form_with(model: [@user, @food], local: true, class: "row") do |f| %>
  <%= f.label :item %>
  <%= f.text_field :item, required: true, autofocus: true %>
  <br />
  <%= f.label :group %>
  <%= f.text_field :group, required: true %>
  <br />
  <br />
  <%= f.submit nil, class: "btn" %>
<% end %>

app/views/foods/edit.html.erb
<h1>Edit Food</h1>

<%= form_with(model: @food, local: true) do |f| %>
  <div class="field">
    <%= f.label :item %>
    <%= f.text_field :item, required: true, placeholder: "Item" %>
  </div>
  <div class="field">
    <%= f.label :group%>
    <%= f.text_field :group, required: true, placeholder:"Group"%>
  </div>
  <%= f.submit %>
<% end %>

app/views/foods/index.html.erb
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<h2>Welcome <%= current_user.first_name %><%=" "%><%= current_user.last_name %></h2>

<hr />

<h3>Your Foods</h3>
<ol>
  <% @foods.each do |food| %>
    <li>
      <%=food.item %> <%="Group:" %>    <%= food.group %>
      <%= link_to "Edit", edit_food_path(food.id) %>
      <%= link_to "Delete", food_path(food.id), method: :delete %>
    </li>
  <% end %>
</ol>

<%= link_to "Add Food", new_food_path, class:"btn green" %>
<%= link_to "Edit User", edit_user_registration_path, class:"btn blue" %>

app/views/foods/new.html.erb
<h1>Add Food</h1>
<%= form_with(model: @food, local: true) do |f| %>
  <div class="field">
    <%= f.label :item %>
    <%= f.text_field :item, autofocus: true, required: true, placeholder: "Item" %>
  </div>
  <div class="field">
    <%= f.label :group%>
    <%= f.text_field :group, required: true, placeholder:"Group"%>
  </div>
  <%= f.submit %>
<% end %>

app/views/foods/show.html.erb
<h1>Foods#show</h1>
<p>Find me in app/views/foods/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<h1><%= @food.id ? 'Edit User' : 'Create User' %></h1>
<hr />
<%= form_with(model: [@user, @food], local: true, class: "row") do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, required: true, autofocus: true %>
  <br />
  <%= f.label :last_name %>
  <%= f.text_field :last_name, required: true %>
  <br />
  <br />
  <%= f.submit nil, class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_with(model: @food, local: true) do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, placeholder: "First Name" %>
  </div>
  <div class="field">
    <%= f.label :last_name%>
    <%= f.text_field :last_name, required: true, placeholder:"Last Name"%>
  </div>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>